### ISSUE TITLE
Get devcontainer indexed in VS Code community containers

### ISSUE THREAD

**Issue by nuvious** [howsoai/howso-devcontainers#20]
VS Code has a dev container wizard to `Add Dev Containers Configuration File` which offers a list of microsoft maintained dev containers but also adds the option to `Show All Definitions...`. This displays a list of community maintained containers:

![image](https://github.com/howsoai/howso-devcontainers/assets/5287736/14912959-ddaa-4b5b-b7da-d1545c035367)

The full list of these containers is maintained [here](https://containers.dev/collections) and to get into this list one only needs to submit a pull request to [this yaml file definition](https://github.com/devcontainers/devcontainers.github.io/blob/gh-pages/_data/collection-index.yml).

The entries for dev container templates take the following format:

```yaml
- name: Templates by John Muchovej
  maintainer: John Muchovej
  contact: https://github.com/jmuchovej/devcontainers/issues
  repository: https://github.com/jmuchovej/devcontainers
  ociReference: ghcr.io/jmuchovej/templates
```

They also seem to use the [devcontainer github action](https://github.com/devcontainers/action) to publish releases that then get picked up by the VS Code community devcontainer scraper. Project structure template is available [here](https://github.com/devcontainers/template-starter).

Will probably get to this in my 'spinning wheels time' waiting for builds so submitting this for documentation/tracking as well as just brain-dumping what I learned about indexing the devcontainer in VS Code.
